### ISSUE TITLE
Handling multiple Codeet instances

### ISSUE THREAD

**Issue by JoaoMosmann** [juanpujol/codeet#6]
As Codeet uses `window.postMessage` method to communicate between editor and origin. It should have a uniqueId generated when creating a new instance, or defined by the user. Because at the moment, if you instantiate more than one Codeet tab, all save postMessage will be interpreted, not differentiating the content.

Example

``` js
codeet.open({
    id: codeet.uniqueId(),
    name: article.title,
    body: article.content,
    callback: function (response) {
        [...]
    }
});
```

Or using a content identifier. So if there is a Codeet instance opened for this content, It would not open a new one, or maybe just share the content between them.

``` js
codeet.open({
    id: 'article/' + article.id,
    name: article.title,
    body: article.content,
    callback: function (response) {
        [...]
    }
});
```

**Comment by juanpujol** [comment]
I like the proposal of a unique ID and I think it could work better if the editor generated this ID and return to the origin with the load confirmation message.

On the editor we can user this id on the route, like `http://juanpujol.github.com/codeet/#!/a45gbs` or something.

Every time an instance of the editor is created from the same origin we just need to be sure to provide a unique id and url path.

@JoaoMosmann What do you think?

**Comment by JoaoMosmann** [comment]
The `id` wasn't necessary. Now it's using just one event listener for all instances, and search for the correct one by comparing the returning object from the method `window.open` and the object that come in the message event `event.source`

**Comment by juanpujol** [comment]
There's still an issue tracking the content of each instance. Please check out the manual tests.

**Comment by juanpujol** [comment]
Seems to work as expected now. Thanks @JoaoMosmann
