### ISSUE TITLE
Add asterisk indicating unsaved document to title

### ISSUE THREAD

**Issue by juanpujol** [juanpujol/codeet#8]
If the document had changes show an asterisks on the title.

![screenshot 2015-04-29 10 08 01](https://cloud.githubusercontent.com/assets/30832/7391495/fde53204-ee57-11e4-92b0-54b205645785.png)

**Comment by JoaoMosmann** [comment]
Done at f3c1aa0a894d9301827672c64dbbe8c14fc3201b
